AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:
  Lambda function to get CSV data from NYC Open Data API and save to S3 Bucket
Globals:
  Function:
    Timeout: 300
    MemorySize: 512
Resources:
  RodentActivityExtractFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: nyc-open-data-extract
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.14
      Architectures:
      - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3DestBucket
      Environment:
        Variables:
          S3_DEST_BUCKET: !Ref S3DestBucket
          S3_REGION: !Ref S3Region

Parameters:
  S3DestBucket:
    Type: String
  S3Region:
    Type: String