AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description:
  Lambda function to get CSV data from NYC Open Data API and save to S3 Bucket
Globals:
  Function:
    Timeout: 300
    MemorySize: 512
Resources:
  ExtractCSVData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.extract
      Runtime: python3.14
      Architectures:
      - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Sub ${S3DestBucket}

Parameters:
  S3DestBucket:
    Type: String