create database stg_nyc_rodent_tracking;
create database dwh_nyc_rodent_tracking;
create database mart_nyc_rodent_tracking;

-- Inspections

create table stg_rodent_inspections (
	":id"	varchar(18),
	":created_at"	timestamp with time zone,
	":updated_at"	timestamp with time zone,
	":version" varchar(17),
	inspection_type varchar(10),
	job_ticket_or_work_order_id int,
	job_id varchar(9),
	job_progress smallint,
	bbl bigint,
	boro_code smallint,
	block int,
	lot smallint,
	house_number varchar(25),
	street_name varchar(150),
	zip_code varchar(10),
	x_coord int,
	y_coord int,
	latitude float,
	longitude float,
	borough varchar(25),
	inspection_date timestamp,
	result varchar(25),
	approved_date timestamp,
	location varchar(50),
	community_board smallint,
	council_district smallint,
	census_tract int,
	bin varchar(15)
);

-- 311 Calls
create table stg_311_service_calls (
	":id"	varchar(18),
	":created_at"	timestamp with time zone,
	":updated_at"	timestamp with time zone,
	":version" varchar(17),
	unique_key int,
	created_date timestamp,
	closed_date timestamp,
	agency Varchar(10),
	agency_name Varchar(100),
	complaint_type Varchar(30),
	descriptor Varchar(50),
	location_type Varchar(50),
	incident_zip Varchar(20),
	incident_address Varchar(75),
	street_name Varchar(50),
	cross_street_1 Varchar(50),
	cross_street_2 Varchar(50),
	intersection_street_1 Varchar(50),
	intersection_street_2 Varchar(50),
	address_type Varchar(15),
	city Varchar(30),
	landmark Varchar(50),
	facility_type Varchar(50),
	status Varchar(15),
	due_date timestamp,
	resolution_description text,
	resolution_action_updated_date timestamp,
	community_board Varchar(30),
	bbl bigint,
	borough Varchar(15),
	x_coordinate_state_plane int,
	y_coordinate_state_plane int,
	open_data_channel_type Varchar(10),
	park_facility_name Varchar(50),
	park_borough Varchar(15),
	vehicle_type Varchar(15),
	taxi_company_borough Varchar(15),
	taxi_pick_up_location Varchar(150),
	bridge_highway_name Varchar(150),
	bridge_highway_direction Varchar(150),
	road_ramp Varchar(150),
	bridge_highway_segment Varchar(250),
	latitude float,
	longitude float,
	location Varchar(50)
);

-- Restaurant Inspections
create table stg_restaurant_inspections (
	":id"	varchar(18),
	":created_at"	timestamp with time zone,
	":updated_at"	timestamp with time zone,
	":version" varchar(17),
	dba Varchar(15),
	boro Varchar(25),
	building Varchar(25),
	street Varchar(150),
	zipcode Varchar(10,
	phone Varchar(25),
	cuisine_description Varchar(50),
	inspection_date timestamp,
	action Varchar(150),
	violation_code Varchar(10),
	violation_description Varchar(150),
	critical_flag Varchar(25),
	score smallint,
	grade Char(1),
	grade_date timestamp,
	record_date timestamp,
	inspection_type Varchar(75),
	latitude float,
	longitude float,
	community_board smallint,
	council_district smallint,
	census_tract int,
	bin Varchar(15),
	bbl bigint,
	nta Varchar(4),
	location_point1 text
)

-- Restaurant Violation codes

